const EVENTS_TYPES={
        START_FETCHING_ALL_EVENTS:      'START_FETCHING_ALL_EVENTS',
        SUCCESS_FETCHING_ALL_EVENTS:    'SSUCCESS_FETCHING_ALL_EVENTS',
        FAILURE_FETCHING_ALL_EVENTS:    'FAILURE_FETCHING_ALL_EVENTS',
        START_ADD_NEW_EVENTS:      'START_ADD_NEW_EVENTS',
        SUCCESS_ADD_NEW_EVENTS:    'SUCCESS_ADD_NEW_EVENTS',
        FAILURE_ADD_NEW_EVENTS:    'FAILURE_ADD_NEW_EVENTS',
}

export default EVENTS_TYPES;